name: Debugging with SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
 
     - name: disk
       run: df -h
     - name: vga 
       run: lspci | grep VGA
     - name: cpu
       run: cat /proc/cpuinfo
    - name: neichun 
       run: free -m
       
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h # Prevent to killing instance after failure
