name: Debugging with SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
 
     - name: Try Build
       run: df -h
            free -m
            lspci | grep VGA
            cat /proc/cpuinfo
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h # Prevent to killing instance after failure
